name: Release

#on:
  #push:
    #tags: [ v* ]
on:
  pull_request:
    branches: [ "main" ]

jobs:
  master_deploy:
    #runs-on: macos-latest
    runs-on: self-hosted

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Import signing certificate into keychain
        run: |
          KEYCHAIN_FILE=default.keychain
          KEYCHAIN_PASSWORD=keychain
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security default-keychain -s $KEYCHAIN_FILE
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security import <(echo $SIGNING_CERTIFICATE_P12_DATA | base64 --decode) \
                          -f pkcs12 \
                          -k $KEYCHAIN_FILE \
                          -P $SIGNING_CERTIFICATE_PASSWORD \
                          -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Archive
        run: |
          xcodebuild -project MockGen.xcodeproj -scheme MockGen -archivePath ./MockGen.xcarchive archive
          
      - name: Export
        run: |
          xcodebuild -exportArchive -archivePath ./MockGen.xcarchive -exportPath ./Release -exportOptionsPlist ExportOptions.plist

      - name: Package
        run: |
          zip -r MockGen.zip Release/MockGen.app

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: MockGen.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
