name: Release

#on:
  #push:
    #tags: [ v* ]
on:
  pull_request:
    branches: [ "main" ]

jobs:
  master_deploy:
    #runs-on: macos-latest
    runs-on: self-hosted

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Archive
        run: |
          xcodebuild -project MockGen.xcodeproj -scheme MockGen -archivePath ./MockGen.xcarchive archive
          
      - name: Export
        run: |
          xcodebuild -exportArchive -archivePath ./MockGen.xcarchive -exportPath ./Release -exportOptionsPlist ExportOptions.plist

      - name: Package
        run: |
          zip -r MockGen.zip Release/MockGen.app

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: MockGen.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
